name = "H5ToVTK"
uuid = "9c1f0060-c7fe-495d-9016-b8e3f873f22e"
authors = ["dhtan <dinghangtan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
